; PlatformIO Project Configuration File for Seeed Studio XIAO ESP32-C3 Solar Weather Sensor
; https://docs.platformio.org/page/projectconf.html

[env:seeed_xiao_esp32c3]
platform = espressif32
board = seeed_xiao_esp32c3
framework = arduino
monitor_speed = 115200

lib_deps =
    https://github.com/tzapu/WiFiManager.git
    adafruit/Adafruit SHT31 Library @ ^2.2.2
    adafruit/Adafruit BusIO @ ^1.17.4
